[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "wolf"
version = "0.1"
authors = [
    {name = "Souheil Chelfouh", email = "trollfot@gmail.com"},
]
requires-python = ">=3.10"
classifiers = ["License :: OSI Approved :: MIT License"]
dependencies = [
  "beartype",
  "autoroutes",
  "chameleon",
  "orjson",
  "svcs",
  "wrapt",
  "sqlmodel",
  "itsdangerous",
  "http_session",
  "vernacular",
  "autorouting",
  "plum-dispatch",
  "pyhamcrest",
  # following the soon-to-be excised from the package
  "deform",
  "colander",
  "pyjwt",
  "kettu",
  "structlog",
  "rich",
]

[project.optional-dependencies]
test = [
    'pytest',
    'webtest'
]

[tool.setuptools.packages.find]
where = ["src"]
include = ["wolf"]
namespaces = false
